platform :ios, '8.0'
use_frameworks!
pod 'AFNetworking'
pod 'PageMenu'
pod 'Parse'
pod 'Google-Maps-iOS-SDK'
pod 'HTPressableButton'
pod 'BFPaperButton'
pod 'pop'
pod 'SCLAlertView'
pod 'RMStepsController'
pod 'IHKeyboardAvoiding'
pod 'JVFloatLabeledTextField'
pod 'TOMSMorphingLabel'
pod 'TSMessages', '~> 0.9.12'
pod 'Canvas', '~> 0.1.2'
